feat: output error messages when validation fails

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -88,6 +88,10 @@ inputs:
     required: false
     description: Validates whether the input value matches the specified regular expression.
 
+outputs:
+  error-message:
+    value: ${{ steps.validate.outputs.error-message }}
+    description: Output error messages when validation fails.
 
 runs:
   using: composite
@@ -146,6 +150,7 @@ runs:
       shell: bash
 
     - name: Run valid
+      id: validate
       env:
         IMAGE_REPO_DIGEST: ${{ steps.image.outputs.repo-digest }}
         VALUE: ${{ inputs.value }}
@@ -290,10 +295,18 @@ runs:
           set +x # disable printing of the command and its arguments
         fi
 
+        log_file="${RUNNER_TEMP}/error-${GITHUB_ACTION}.log"
         docker run --interactive --rm --user 1111:1111 --read-only \
           --security-opt no-new-privileges --cap-drop all --network none \
-          "${IMAGE_REPO_DIGEST}" "${flags[@]}"
+          "${IMAGE_REPO_DIGEST}" "${flags[@]}" 2>"${log_file}" || ret="$?"
+
+        if [[ -f "${log_file}" ]]; then
+          message="$(cat "${log_file}")"
+          echo "error-message=${message}" >> "${GITHUB_OUTPUT}"
+          echo "${message}"
+        fi
         echo "::endgroup::"
+        exit "${ret:-0}"
       shell: bash
 
 branding:
